@startuml

autonumber
header: Core
title: Create an authorization to connect to a Service that is offered on behalf of another Peer

box "Consuming Peer"
  participant "Manager" as managerConsumingPeer
end box

box "Providing Peer"
  participant "Manager" as managerProvidingPeer
end box

box "Delegator Service Publication"
  participant "Manager" as managerDelegatorServicePublication
end box

managerConsumingPeer -> managerConsumingPeer: Create Contract with a __ServiceConnectionGrant__
managerConsumingPeer -> managerConsumingPeer: Sign Contract
managerConsumingPeer -> managerProvidingPeer: Submit Contract
managerConsumingPeer -> managerDelegatorServicePublication: Submit Contract
managerProvidingPeer -> managerProvidingPeer: Sign Contract
managerProvidingPeer -> managerConsumingPeer: Accept Contract
managerProvidingPeer -> managerDelegatorServicePublication: Accept Contract
managerDelegatorServicePublication -> managerDelegatorServicePublication: Sign Contract
managerDelegatorServicePublication -> managerProvidingPeer: Accept Contract
managerDelegatorServicePublication -> managerConsumingPeer: Accept Contract

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox

@enduml
