sequenceDiagram
    participant ConsumerADL as Consumer<br/>Decision Log
    participant ConsumerPDP as Consumer<br/>Decision Point
    actor User
    participant Consumer as Consumer<br/>Outway PEP
    participant Provider as Provider<br/>Inway PEP
    participant ProviderPDP as Provider<br/>Decision Point
    participant ProviderADL as Provider<br/>Decision Log
    User-->>+Consumer: request
    Consumer-->>+ConsumerPDP:allowed?
    ConsumerPDP-->>ConsumerADL:log record
    ConsumerPDP-->>-Consumer:yes
    Consumer-->>+Provider: 
    Provider-->>+ProviderPDP: allowed?
    ProviderPDP-->>ProviderADL:log record
    ProviderPDP-->>-Provider: yes
    Provider-->>-Consumer: 
    Consumer-->>-User: response